name: projek_uas
description: ini adalah projek uas 3found (irfanda, dezenda, permana)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  qrscan: ^0.1.6
  simple_permissions: ^0.1.9

dev_dependencies:
  http: 0.12.2
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
 

# font
flutter:
  assets:
    - assets/image/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  fonts:
#arial
    - family: Arialn
      fonts:
        - asset: assets/fonts/arial/Arialn.ttf
    - family: ArialBlack 
      fonts:
        - asset: assets/fonts/arial/ariblk.ttf
#calibri

    - family: CalibriBold
      fonts:
        - asset: assets/fonts/calibri/Calibri Bold.TTF
    - family: CalibriBoldItalic
      fonts:
        - asset: assets/fonts/calibri/Calibri Bold Italic.ttf
    - family: CalibriItalic
      fonts:
         - asset: assets/fonts/calibri/Calibri Italic.ttf
    - family: CalibriLight
      fonts:
         - asset: assets/fonts/calibri/Calibri Light.ttf
    - family: CalibriLightItalic
      fonts:
       - asset: assets/fonts/calibri/Calibri Light Italic.ttf
    - family: CalibriLightItalic
      fonts:
       - asset: assets/fonts/calibri/Calibri Regular.ttf

    #Segoe UI
    - family: SegoeUI
      fonts:
       - asset: assets/fonts/segoeui/Segoe UI.ttf
    - family: SegoeUIBold
      fonts:
        - asset: assets/fonts/segoeui/Segoe UI Bold.ttf
    - family: SegoeUIBoldItalic
      fonts:
       - asset: assets/fonts/segoeui/Segoe UI Bold Italic.ttf

    - family: SegoeUIItalic
      fonts:
       - asset: assets/fonts/segoeui/Segoe UI Italic.ttf
